In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3 as sql

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
# Se carga el archivo final depurado de la primera parte del ejercicio a un data frame de pandas
TLT_propuesto = pd.read_csv('/content/drive/MyDrive/ESP_BigData/GYADD/Proyecto/reporte_TLT_propuesto.csv')

In [4]:
TLT_propuesto.head(20) # Verificacion y carga de los archivos

,Source_Dest,*Source,PO,OriginCity,OriginState,OriginCountry,OriginName,GoodsSupplier,SupplierNumber,Supplier,...,Total Lead Time,Total Lead Time(hist),Media_TLT_lane,Std_TLT_lane,TLT_Outlier,TLT_hist_no_outlier,Cajas_no_outlier,SumCajas_no_outlier,TLT_ponderado,TLT_propuesto
0,100033-7015313501-BOLI,100033-701531,3371549,NORTH BERGEN,NJ,USA,EDI_100033_WESTERN NJ 83,701531,100033,PERNOD RICARD USA,...,23.0,10.0,19.903509,9.905529,False,10.0,948.0,30481.0,0.311013,18.0
1,112257-7012717201-LASV,112257-701271,3440659,NORTH BERGEN,NJ,USA,WESTERN CARRIERS NJ 2220 91 BLDG 5,701271,112257,BERTRANDS WINES/MHW LTD,...,29.0,15.0,39.666667,38.501631,False,15.0,56.0,168.0,5.000000,17.0
2,104522-7002875101-1000,104522-700287,3440693,WOODRIDGE,IL,USA,EDI_104522_CHICAGO RDC IL,700287,104522,EJ GALLO WINERY,...,3.0,2.0,5.072917,3.905410,False,2.0,1368.0,398800.0,0.006861,5.0
3,100478-7015425401-BULK,100478-701542,3440712,LEXINGTON,KY,USA,EDI_100478_CAMPARI LEX KY,701542,100478,CAMPARI AMERICA,...,19.0,23.0,22.952381,11.375987,False,23.0,243.0,2957.0,1.890091,20.0
4,102571-7012719201-1000,102571-701271,3440727,NORTH BERGEN,NJ,USA,WESTERN CARRIERS NJ 2220 91 BLDG 5,701271,102571,CAPE CLASSICS,...,30.0,16.0,19.333333,3.297558,True,NaN,NaN,37.0,NaN,19.0
5,104522-7008009501-1000,104522-700800,3440729,KANSAS CITY,KS,USA,EDI_104522_METRO PRK WHSE,700800,104522,EJ GALLO WINERY,...,4.0,2.0,5.579634,12.324018,False,2.0,1582.0,536856.0,0.005894,4.0
6,104522-7008009502-1000,104522-700800,3440795,KANSAS CITY,KS,USA,EDI_104522_METRO PRK WHSE,700800,104522,EJ GALLO WINERY,...,4.0,2.0,3.461353,2.010123,False,2.0,1942.0,571984.0,0.006790,4.0
7,104522-7010159201-1000,104522-701015,3440844,FORT WORTH,TX,USA,EDI_104522_SADDLE CREEK TX,701015,104522,EJ GALLO WINERY,...,5.0,2.0,5.211886,7.388524,False,2.0,1093.0,597778.0,0.003657,5.0
8,104522-7010158702-1000,104522-701015,3440878,FORT WORTH,TX,USA,EDI_104522_SADDLE CREEK TX,701015,104522,EJ GALLO WINERY,...,4.0,3.0,4.642005,4.421439,False,3.0,1305.0,1714070.0,0.002284,5.0
9,100478-7015469502-1000,100478-701546,3440893,NORTH BERGEN,NJ,USA,EDI_100478_WESTERN NJ 83,701546,100478,CAMPARI AMERICA,...,16.0,23.0,15.593220,4.595703,True,NaN,NaN,10561.0,NaN,15.0
10,104522-7010158702-1000,104522-701015,3440895,FORT WORTH,TX,USA,EDI_104522_SADDLE CREEK TX,701015,104522,EJ GALLO WINERY,...,4.0,3.0,4.642005,4.421439,False,3.0,1201.0,1714070.0,0.002102,5.0
11,115151-7012668704-1000,115151-701266,3440929,AMERICAN CANYON,CA,USA,WESTERN CA 875,701266,115151,ASAHI BEER USA/MHW LTD,...,42.0,48.0,39.727273,10.888799,False,48.0,237.0,2352.0,4.836735,38.0
12,100528-7016933501-BOLI,100528-701693,3440961,LODI,CA,USA,EDI_100528_TRINCHERO FAMILY ESTATES,701693,100528,SUTTER HOME WINERY INC,...,39.0,42.0,37.775000,9.465651,False,42.0,2531.0,168401.0,0.631243,39.0
13,104326-7012688701-1000,104326-701268,3441029,NORTH BERGEN,NJ,USA,WESTERN NJ 71,701268,104326,CAROLINA WINE BRANDS/MHW LTD,...,37.0,122.0,45.000000,44.776221,True,NaN,NaN,65.0,NaN,26.0
14,100501-7015509201-1000,100501-701550,3441044,BURBANK,WA,USA,EDI_100501_NW WINE SERVICES,701550,100501,STE MICHELLE WINE ESTATES,...,59.0,20.0,36.500000,18.851041,False,20.0,1148.0,20451.0,1.122683,32.0
15,104326-7012685102-1000,104326-701268,3441046,NORTH BERGEN,NJ,USA,WESTERN NJ 71,701268,104326,CAROLINA WINE BRANDS/MHW LTD,...,30.0,29.0,26.000000,3.450000,False,29.0,113.0,117.0,28.008547,29.0
16,102571-7029638701-1000,102571-702963,3441061,SOMERSET WEST,OS,ZAF,LOURENSFORD WINE ESTATE,702963,102571,CAPE CLASSICS,...,123.0,167.0,167.000000,0.000000,False,167.0,700.0,700.0,167.000000,167.0
17,100224-7012713501-BOLI,100224-701271,3441093,NORTH BERGEN,NJ,USA,WESTERN CARRIERS NJ 2220 91 BLDG 5,701271,100224,FREDERICK WILDMAN SONS,...,22.0,17.0,22.833333,12.709393,False,17.0,46.0,3823.0,0.204551,22.0
18,100333-7012643501-BOLI,100333-701264,3441110,AMERICAN CANYON,CA,USA,WESTERN CA 1275,701264,100333,MAISONS MARQUES DOMAINES USA INC,...,28.0,34.0,28.962264,10.283395,False,34.0,51.0,3473.0,0.499280,29.0
19,100402-7062136401-OTHR,100402-706213,3441129,BENICIA,CA,USA,EDI_100402_CRU_ONLY_SANTA CLARA,706213,100402,TERLATO WINES INTERNATIONAL,...,24.0,23.0,20.500000,4.441542,False,23.0,36.0,147.0,5.632653,24.0

In [5]:
# Se carga uno de los archivos de dimensiones como dataframe de pandas
Bodegas_Info =pd.read_excel('/content/drive/MyDrive/ESP_BigData/GYADD/Proyecto/SGWarehouses.xlsx',sheet_name='WH Adresses')

In [6]:
Carriles_df = pd.read_csv('/content/drive/MyDrive/ESP_BigData/GYADD/Proyecto/Network_-_.csv')

<ipython-input-6-34b5d7fdcafb>:1: DtypeWarning: Columns (21,33,34) have mixed types. Specify dtype option on import or set low_memory=False.
  Carriles_df = pd.read_csv('/content/drive/MyDrive/ESP_BigData/GYADD/Proyecto/Network_-_.csv')

In [7]:
# Definicion de ubicacion y nombre del archivo de base de datos de sqlite
base_de_datos = '/content/drive/MyDrive/ESP_BigData/GYADD/Proyecto/proyecto_db.db'

In [8]:
def createDB():
  conn = sql.connect(base_de_datos)
  conn.commit() #
  conn.close() # por buenas practicas se cierra la base de datos luego de creada
  print("Cree la base de datos")

In [9]:
createDB() # Se conecta a la base de datos o la crea si no existe

Cree la base de datos

In [10]:
conn = sql.connect(base_de_datos)
cursor = conn.cursor()
TLT_propuesto.to_sql('TLT_propuesto_tabla',conn,if_exists='replace',index=False)
cursor.close()
conn.close()

In [11]:
conn = sql.connect(base_de_datos)
cursor = conn.cursor()
Bodegas_Info.to_sql('Bodegas_Info_tabla',conn,if_exists='replace',index=False)
cursor.close()
conn.close()

In [12]:
conn = sql.connect(base_de_datos)
cursor = conn.cursor()
Carriles_df.to_sql('Carriles_tabla',conn,if_exists='replace',index=False)
cursor.close()
conn.close()

In [13]:
def seleccionaFilas(campo,numrecords):
  conn = sql.connect(base_de_datos)
  cursor=conn.cursor()
  query = f"SELECT * FROM TLT_propuesto_tabla ORDER by {campo} DESC LIMIT {numrecords};"
  cursor.execute(query)
  datos=cursor.fetchall() # para enviarlo a una variable de Python y poder visualizar
  conn.commit()
  for row in datos:
    print(row)
  cursor.close()
  conn.close()

In [14]:
seleccionaFilas('OriginCity',10) # Seleccion e impresion de registros en la tabla TLT_propuesto_tabla

('101723-7017121401-BULK', '101723-701712', 3463794, 'ZIERBENA', 'OS', 'ESP', 'STOKIA XXI S.L', 701712, 101723, 'VIN DIVINO DBA GONZALEZ BYASS', 'LAKELAND', 'FL', '2023-01-25', '2/20/2023', '3/30/2023', '2/20/2023', '1/26/2023', '2023-04-21', 'Closed', None, 898, 'Collect', 'N', None, None, 'LAKELAND', '1401-BULK', 21.0, 42.0, 1.0, 64.0, 86.0, 77.4, 11.80865784075396, 0, 86.0, 898.0, 2968.0, 26.02021563342318, 78.0)
('101723-7017121401-BULK', '101723-701712', 3493590, 'ZIERBENA', 'OS', 'ESP', 'STOKIA XXI S.L', 701712, 101723, 'VIN DIVINO DBA GONZALEZ BYASS', 'LAKELAND', 'FL', '2023-02-23', '4/6/2023', '4/25/2023', '4/6/2023', '2/27/2023', '2023-05-02', 'Closed', 'MULTI', 738, 'Collect', 'Y', '4/24/2023', '4/25/2023', 'LAKELAND', '1401-BULK', 21.0, 42.0, 1.0, 64.0, 68.0, 77.4, 11.80865784075396, 0, 68.0, 738.0, 2968.0, 16.90835579514825, 78.0)
('101723-7017128702-1000', '101723-701712', 3488734, 'ZIERBENA', 'OS', 'ESP', 'STOKIA XXI S.L', 701712, 101723, 'VIN DIVINO DBA GONZALEZ BYASS', 'KATY', 'TX', '2023-02-20', '4/10/2023', '6/9/2023', '4/10/2023', '2/24/2023', '2023-06-13', 'Closed', 'MULTI', 350, 'Collect', 'Y', '5/24/2023', '6/9/2023', 'KATY', '8702-1000', 21.0, 63.0, 1.0, 85.0, 113.0, 97.33333333333331, 12.748355013708847, 1, None, None, 905.0, None, 90.0)
('101723-7017128702-1000', '101723-701712', 3522075, 'ZIERBENA', 'OS', 'ESP', 'STOKIA XXI S.L', 701712, 101723, 'VIN DIVINO DBA GONZALEZ BYASS', 'KATY', 'TX', '2023-03-23', '4/12/2023', '5/23/2023', '4/12/2023', '3/27/2023', '2023-06-21', 'Closed', 'MULTI', 710, 'Collect', 'Y', '5/23/2023', '5/23/2023', 'KATY', '8702-1000', 21.0, 63.0, 1.0, 85.0, 90.0, 97.33333333333331, 12.748355013708847, 0, 90.0, 710.0, 905.0, 70.60773480662984, 90.0)
('101723-7017126201-STFE', '101723-701712', 3507291, 'ZIERBENA', 'OS', 'ESP', 'STOKIA XXI S.L', 701712, 101723, 'VIN DIVINO DBA GONZALEZ BYASS', 'SANTA FE SPRINGS', 'CA', '2023-03-09', '3/26/2023', '5/4/2023', '3/26/2023', '3/13/2023', '2023-05-08', 'Closed', 'MULTI', 1189, 'Collect', 'Y', '5/4/2023', '5/4/2023', 'SANTA FE SPRINGS', '6201-STFE', 21.0, 56.0, 1.0, 78.0, 60.0, 79.75, 16.593009635084286, 1, None, None, 1631.0, None, 87.0)
('101723-7017126201-STFE', '101723-701712', 3548706, 'ZIERBENA', 'OS', 'ESP', 'STOKIA XXI S.L', 701712, 101723, 'VIN DIVINO DBA GONZALEZ BYASS', 'SANTA FE SPRINGS', 'CA', '2023-04-20', '5/25/2023', '7/13/2023', '5/25/2023', '4/21/2023', '2023-07-21', 'Closed', None, 253, 'Collect', 'N', None, None, 'SANTA FE SPRINGS', '6201-STFE', 21.0, 56.0, 1.0, 78.0, 92.0, 79.75, 16.593009635084286, 0, 92.0, 253.0, 1631.0, 14.270999386879216, 87.0)
('112349-7017121401-BULK', '112349-701712', 3537798, 'ZIERBENA', 'OS', 'ESP', 'STOKIA XXI S.L', 701712, 112349, 'EUROPEAN CELLARS/USA WINE WEST', 'LAKELAND', 'FL', '2023-04-11', '6/6/2023', '7/13/2023', '6/6/2023', '4/12/2023', '2023-07-19', 'Closed', 'MULTI', 341, 'Collect', 'Y', '7/31/2023', '8/1/2023', 'LAKELAND', '1401-BULK', 42.0, 39.0, 1.0, 82.0, 99.0, 82.0, 16.45210219597078, 1, None, None, 13.0, None, 83.0)
('101723-7017121401-BULK', '101723-701712', 3530191, 'ZIERBENA', 'OS', 'ESP', 'STOKIA XXI S.L', 701712, 101723, 'VIN DIVINO DBA GONZALEZ BYASS', 'LAKELAND', 'FL', '2023-03-30', '4/26/2023', '5/26/2023', '4/27/2023', '3/31/2023', '2023-06-02', 'Closed', 'MULTI', 977, 'Collect', 'Y', '5/25/2023', '5/26/2023', 'LAKELAND', '1401-BULK', 21.0, 42.0, 1.0, 64.0, 64.0, 77.4, 11.80865784075396, 1, None, None, 2968.0, None, 78.0)
('112349-7017121401-BULK', '112349-701712', 3565067, 'ZIERBENA', 'OS', 'ESP', 'STOKIA XXI S.L', 701712, 112349, 'EUROPEAN CELLARS/USA WINE WEST', 'LAKELAND', 'FL', '2023-05-09', '6/2/2023', '7/6/2023', '6/2/2023', '5/10/2023', '2023-07-12', 'Closed', 'MULTI', 1, 'Collect', 'Y', '7/5/2023', '7/6/2023', 'LAKELAND', '1401-BULK', 42.0, 39.0, 1.0, 82.0, 64.0, 82.0, 16.45210219597078, 1, None, None, 13.0, None, 83.0)
('101723-7017126201-STFE', '101723-701712', 3566077, 'ZIERBENA', 'OS', 'ESP', 'STOKIA XXI S.L', 701712, 101723, 'VIN DIVINO DBA GONZALEZ BYASS', 'SANTA FE SPRINGS', 'CA', '2023-05-10', '5/26/2023', '7/13/2023', '5/26/2023', '5/10/2023', '2023-07-21', 'Closed', None, 586, 'Collect', 'N', None, None, 'SANTA FE SPRINGS', '6201-STFE', 21.0, 56.0, 1.0, 78.0, 72.0, 79.75, 16.593009635084286, 0, 72.0, 586.0, 1631.0, 25.86879215205396, 87.0)

In [15]:
# Muestra la informacion de las columnas en la tabla TLT_propuesto_tabla
conn=sql.connect(base_de_datos)
cursor=conn.cursor()
query=f"pragma table_info(TLT_propuesto_tabla);"
cursor.execute(query)
datos=cursor.fetchall()
for row in datos:
    print(row)
cursor.close()
conn.close()

(0, 'Source_Dest', 'TEXT', 0, None, 0)
(1, '*Source', 'TEXT', 0, None, 0)
(2, 'PO', 'INTEGER', 0, None, 0)
(3, 'OriginCity', 'TEXT', 0, None, 0)
(4, 'OriginState', 'TEXT', 0, None, 0)
(5, 'OriginCountry', 'TEXT', 0, None, 0)
(6, 'OriginName', 'TEXT', 0, None, 0)
(7, 'GoodsSupplier', 'INTEGER', 0, None, 0)
(8, 'SupplierNumber', 'INTEGER', 0, None, 0)
(9, 'Supplier', 'TEXT', 0, None, 0)
(10, 'DestinationCity', 'TEXT', 0, None, 0)
(11, 'DestinationState', 'TEXT', 0, None, 0)
(12, 'CreateDateTime', 'TEXT', 0, None, 0)
(13, 'CurrentRSD', 'TEXT', 0, None, 0)
(14, 'CurrentRDD', 'TEXT', 0, None, 0)
(15, 'PickDepart', 'TEXT', 0, None, 0)
(16, 'FulfilledDate', 'TEXT', 0, None, 0)
(17, 'GR_Date', 'TEXT', 0, None, 0)
(18, 'LoadStatus', 'TEXT', 0, None, 0)
(19, 'MultiLeg', 'TEXT', 0, None, 0)
(20, 'Cases', 'INTEGER', 0, None, 0)
(21, 'TermsType', 'TEXT', 0, None, 0)
(22, 'CALC_MULTI_LEG_CHECK', 'TEXT', 0, None, 0)
(23, 'CALC_PICKDATE_MULTILEG', 'TEXT', 0, None, 0)
(24, 'CALC_DROPDATE_MULTILEG', 'TEXT', 0, None, 0)
(25, 'City', 'TEXT', 0, None, 0)
(26, 'DEST', 'TEXT', 0, None, 0)
(27, 'LoadTime', 'REAL', 0, None, 0)
(28, 'TransLeadTime', 'REAL', 0, None, 0)
(29, 'UnloadTime', 'REAL', 0, None, 0)
(30, 'Total Lead Time', 'REAL', 0, None, 0)
(31, 'Total Lead Time(hist)', 'REAL', 0, None, 0)
(32, 'Media_TLT_lane', 'REAL', 0, None, 0)
(33, 'Std_TLT_lane', 'REAL', 0, None, 0)
(34, 'TLT_Outlier', 'INTEGER', 0, None, 0)
(35, 'TLT_hist_no_outlier', 'REAL', 0, None, 0)
(36, 'Cajas_no_outlier', 'REAL', 0, None, 0)
(37, 'SumCajas_no_outlier', 'REAL', 0, None, 0)
(38, 'TLT_ponderado', 'REAL', 0, None, 0)
(39, 'TLT_propuesto', 'REAL', 0, None, 0)

In [16]:
def sumarizaTLT(porcampo):
  numregistros=int(input("Ingrese el numero de lineas a visualizar: "))
  conn=sql.connect(base_de_datos)
  cursor=conn.cursor()
  query = f"""
  SELECT {porcampo}, SUM(TLT_propuesto)
  FROM TLT_propuesto_tabla
  GROUP BY {porcampo}
  LIMIT {numregistros}
  """
  cursor.execute(query)
  results=cursor.fetchall()
  for result in results:
    print(result)
  cursor.close()
  conn.close()

In [17]:
sumarizaTLT('Source_Dest')

Ingrese el numero de lineas a visualizar: 10
('100003-7000747201-LASV', 12.0)
('100003-7012635101-1000', 40.0)
('100003-7012637201-LASV', 24.0)
('100003-7012637202-SPAR', 34.0)
('100003-7012638701-1000', 26.0)
('100003-7012639501-1000', 24.0)
('100003-7012639502-1000', 28.0)
('100003-7012703501-BOLI', 133.0)
('100003-7012705101-1000', 266.0)
('100003-7012707201-LASV', 58.0)

In [18]:
# Seleccion de todos los registros donde un campo toma un valor especifico
conn=sql.connect(base_de_datos)
cursor=conn.cursor()
query="SELECT * FROM TLT_propuesto_tabla WHERE Source_Dest IS '100033-7013427201-LASV';"
cursor.execute(query)
datos=cursor.fetchall()
for result in datos:
    print(result)
cursor.close()
conn.close()

('100033-7013427201-LASV', '100033-701342', 3460309, 'PAISLEY', 'OS', 'GBR', 'EDI_100033_CHIVAS BROS PAISLEY', 701342, 100033, 'PERNOD RICARD USA', 'LAS VEGAS', 'NV', '2023-01-23', '4/18/2023', '5/24/2023', None, '4/14/2023', '2023-05-24', 'Closed', 'MULTI', 1027, 'Prepaid', 'Y', '5/23/2023', '5/24/2023', 'LAS VEGAS', '7201-LASV', 56.0, 68.0, 1.0, 125.0, 121.0, 101.0, 23.0, 0, 121.0, 1027.0, 2755.0, 45.1059891107078, 96.0)
('100033-7013427201-LASV', '100033-701342', 3541429, 'PAISLEY', 'OS', 'GBR', 'EDI_100033_CHIVAS BROS PAISLEY', 701342, 100033, 'PERNOD RICARD USA', 'LAS VEGAS', 'NV', '2023-04-13', '6/19/2023', '7/4/2023', None, '6/15/2023', '2023-07-03', 'Closed', 'MULTI', 1728, 'Prepaid', 'Y', '7/3/2023', '7/4/2023', 'LAS VEGAS', '7201-LASV', 56.0, 68.0, 1.0, 125.0, 81.0, 101.0, 23.0, 0, 81.0, 1728.0, 2755.0, 50.80508166969147, 96.0)

#CRUD Aplicado a una de las tablas de la base de datos.

Se escogera una de las tablas de dimension, la que contiene la informacion de las bodegas. Esto para no afectar el reporte final

In [19]:
def imprimenrecords(nom_tabla,num_records):
  conn=sql.connect(base_de_datos)
  cursor=conn.cursor()
  query=f"SELECT * FROM {nom_tabla} LIMIT {num_records};"
  cursor.execute(query)
  datos=cursor.fetchall()
  for info in datos:
      print(info)
  cursor.close()
  conn.close()

In [20]:
# Conexion a la tabla e impresion de los primeros 10 registros
imprimenrecords('Bodegas_Info_tabla',10)

('1401-BULK', '1401-Florida', 'Florida', 'FL/SC', 'FL', 'FL', '4400 OLD TAMPA HIGHWAY', 'LAKELAND', 33811, 'FL', 'US', 'East', 'Lakeland, FL')
('2201-LOUI', '2201-Kentucky', 'Kentucky', 'NO', 'KY', 'KY', '2801 CONSTANT COMMENT PLACE', 'LOUISVILLE', 40299, 'KY', 'US', 'East', 'Louisville, KY')
('2501-BULK', '2501-Indiana', 'Indiana', 'NO', 'IN', 'IN', '3901 HANNA CIRCLE', 'INDIANAPOLIS', 46241, 'IN', 'US', 'Central', 'Greenwood, IN')
('3201-COLU', '3201-South Carolina', 'South Carolina', 'FL/SC', 'SC', 'SC', '7600 RICHARD STREET', 'COLUMBIA', 29209, 'SC', 'US', 'East', 'Columbia, SC')
('3501-BOLI', '3501-Illinois', 'Illinois', 'NO', 'IL', 'IL', '300 EAST CROSSROADS PARKWAY', 'BOLINGBROOK', 60440, 'IL', 'US', 'Central', 'Bolingbrook, IL')
('4201-BULK', '4201-Pennsylvania', 'Pennsylvania', 'NO', 'PA', 'PA', '536 JONES BLVD', 'POTTSTOWN', 19464, 'PA', 'US', 'East', 'Pennsylvania, PA')
('4501-LIND', '4501-New York-Linden', 'New York-Linden', 'NEW YORK', 'NY', 'NY-L', '801 West Linden Avenue', 'Linden', 7036, 'NJ', 'US', 'East', 'Linden, NY')
('4501-METR', '4501-New York-Syosset', 'New York-Syosset', 'NEW YORK', 'NY', 'NY-M', '345 UNDERHILL BLVD', 'SYOSSET', 11791, 'NY', 'US', 'East', 'Syosset, NY')
('4601-SL01', '4601-New York-Syracuse', 'New York-Syracuse', 'NEW YORK', 'NY', 'NY-U', '3063 COURT STREET', 'SYRACUSE', 13208, 'NY', 'US', 'East', 'Syracuse, NY')
('5101-1000', '5101-Ohio-Columbus', 'Ohio-Columbus', 'OHIO', 'OH', 'OH-CO', '4800 PORTH ROAD', 'COLUMBUS', 43213, 'OH', 'US', 'East', 'Columbus, OH')

In [21]:
# Impresion de la informacion de las columnas que componen la tabla. El query presentado retornara:
# cid: El id de la columna
# name: El nombre de la columna
# type: El tipo de dato
# notnull: Si la columna es null
# dflt_value: El valor por defecto de la columna
# pk: Si la columna tiene una llave primaria
conn=sql.connect(base_de_datos)
cursor=conn.cursor()
query=f"pragma table_info(Bodegas_Info_tabla)" #
cursor.execute(query)
datos=cursor.fetchall()
for row in datos:
    print(row)
cursor.close()
conn.close()

(0, 'DEST', 'TEXT', 0, None, 0)
(1, 'Plant-Desc', 'TEXT', 0, None, 0)
(2, 'Description', 'TEXT', 0, None, 0)
(3, 'MULTIPLE DIVISION', 'TEXT', 0, None, 0)
(4, 'Abrev.', 'TEXT', 0, None, 0)
(5, 'division', 'TEXT', 0, None, 0)
(6, 'Street', 'TEXT', 0, None, 0)
(7, 'City', 'TEXT', 0, None, 0)
(8, 'Postal Code', 'INTEGER', 0, None, 0)
(9, 'Region', 'TEXT', 0, None, 0)
(10, 'Country', 'TEXT', 0, None, 0)
(11, 'Jackson, MS 39203', 'TEXT', 0, None, 0)
(12, 'Desc LT', 'TEXT', 0, None, 0)

In [22]:
# Insercion de un registro. Este registro lo insertara al final de la tabla
conn=sql.connect(base_de_datos)
cursor=conn.cursor()
query = """
INSERT INTO Bodegas_Info_tabla(DEST,'Plant-Desc',Description,'MULTIPLE DIVISION','Abrev.',division,Street,City,'Postal Code',Region,Country,'Jackson, MS 39203','Desc LT')
VALUES ('1111-BULK','1111-Florida','Florida','FLN/FLS','FL','FL-S','1234 OLD TAMPA HIGHWAY','LAKELAND','33324','FL','US','East','Lakeland, FL');
"""
cursor.execute(query)
conn.commit()
cursor.close()
conn.close()

In [23]:
# Verificacion de la insercion del registro
conn=sql.connect(base_de_datos)
cursor=conn.cursor()
query="SELECT * FROM Bodegas_Info_tabla;"
cursor.execute(query)
datos=cursor.fetchall()
for info in datos:
    print(info)
cursor.close()
conn.close()

('1401-BULK', '1401-Florida', 'Florida', 'FL/SC', 'FL', 'FL', '4400 OLD TAMPA HIGHWAY', 'LAKELAND', 33811, 'FL', 'US', 'East', 'Lakeland, FL')
('2201-LOUI', '2201-Kentucky', 'Kentucky', 'NO', 'KY', 'KY', '2801 CONSTANT COMMENT PLACE', 'LOUISVILLE', 40299, 'KY', 'US', 'East', 'Louisville, KY')
('2501-BULK', '2501-Indiana', 'Indiana', 'NO', 'IN', 'IN', '3901 HANNA CIRCLE', 'INDIANAPOLIS', 46241, 'IN', 'US', 'Central', 'Greenwood, IN')
('3201-COLU', '3201-South Carolina', 'South Carolina', 'FL/SC', 'SC', 'SC', '7600 RICHARD STREET', 'COLUMBIA', 29209, 'SC', 'US', 'East', 'Columbia, SC')
('3501-BOLI', '3501-Illinois', 'Illinois', 'NO', 'IL', 'IL', '300 EAST CROSSROADS PARKWAY', 'BOLINGBROOK', 60440, 'IL', 'US', 'Central', 'Bolingbrook, IL')
('4201-BULK', '4201-Pennsylvania', 'Pennsylvania', 'NO', 'PA', 'PA', '536 JONES BLVD', 'POTTSTOWN', 19464, 'PA', 'US', 'East', 'Pennsylvania, PA')
('4501-LIND', '4501-New York-Linden', 'New York-Linden', 'NEW YORK', 'NY', 'NY-L', '801 West Linden Avenue', 'Linden', 7036, 'NJ', 'US', 'East', 'Linden, NY')
('4501-METR', '4501-New York-Syosset', 'New York-Syosset', 'NEW YORK', 'NY', 'NY-M', '345 UNDERHILL BLVD', 'SYOSSET', 11791, 'NY', 'US', 'East', 'Syosset, NY')
('4601-SL01', '4601-New York-Syracuse', 'New York-Syracuse', 'NEW YORK', 'NY', 'NY-U', '3063 COURT STREET', 'SYRACUSE', 13208, 'NY', 'US', 'East', 'Syracuse, NY')
('5101-1000', '5101-Ohio-Columbus', 'Ohio-Columbus', 'OHIO', 'OH', 'OH-CO', '4800 PORTH ROAD', 'COLUMBUS', 43213, 'OH', 'US', 'East', 'Columbus, OH')
('5102-1000', '5102-Ohio-Glenwillow', 'Ohio-Glenwillow', 'OHIO', 'OH', 'OH-CL', '7800 COCHRAN ROAD', 'GLENWILLOW', 44139, 'OH', 'US', 'East', 'Glenwillow (Cleveland), OH ')
('5201-BULK', '5201-Arizona', 'Arizona', 'NO', 'AZ', 'AZ', '2375 S 45th AVE', 'PHOENIX', 85043, 'AZ', 'US', 'West', 'Phoenix, AZ')
('5301-BULK', '5301-Wash DC', 'Wash DC', 'MARYLAND & CISTRIC OF COLUMBIA', 'DC', 'DC', '7001 QUAD AVENUE', 'BALTIMORE', 21237, 'MD', 'US', 'East', 'Wash DC')
('5401-BULK', '5401-Delaware', 'Delaware', 'NO', 'DE', 'DE', '615 LAMBSON LANE', 'NEW CASTLE', 19720, 'DE', 'US', 'East', 'Newcastle, DE')
('5501-BULK', '5501-Maryland', 'Maryland', 'MARYLAND & CISTRIC OF COLUMBIA', 'MD', 'MD', '7001 QUAD AVENUE', 'BALTIMORE', 21237, 'MD', 'US', 'East', 'Baltimore, MD')
('5601-BULK', '5601-Minnesota', 'Minnesota', 'Minnesota & North & South Dakota', 'MN', 'MN', '3350 4th AVENUE EAST', 'SHAKOPEE', 55379, 'MN', 'US', 'Central', 'Shakopee, MN')
('5701-NBLK', '5701-North Dakota', 'North Dakota', 'Minnesota & North & South Dakota', 'ND', 'ND', '3350 4TH AVENUE EAST', 'SHAKOPEE', 55379, 'MN', 'US', 'Central', 'North Dakota')
('5801-SBLK', '5801-South Dakota', 'South Dakota', 'Minnesota & North & South Dakota', 'SD', 'SD', '3350 4TH AVENUE EAST', 'SHAKOPEE', 55379, 'MN', 'US', 'Central', 'South Dakota')
('5901-BULK', '5901-Nebraska', 'Nebraska', 'NO', 'NE', 'NE', '4433 SOUTH 96TH STREET', 'OMAHA', 68127, 'NE', 'US', 'Central', 'Omaha, NE')
('6201-STFE', '6201-California-Santa Fe Springs', 'California-Santa Fe Springs', 'CALIFORNIA', 'CA', 'CA-S', '13500 FOSTER ROAD', 'SANTA FE SPRINGS', 90670, 'CA', 'US', 'West', 'Santa Fe, CA')
('6401-OTHR', '6401-California-Union City', 'California-Union City', 'CALIFORNIA', 'CA', 'CA-N', '1555 ATLANTIC STREET', 'UNION CITY', 94587, 'CA', 'US', 'West', 'Union City, CA')
('6601-KAHU', '6601-Hawaii-Maui ', 'Hawaii-Maui ', 'HAWAII', 'HI', 'HI-M', '231 LALO PLACE KAHULUI', 'MAUI', 96732, 'HI', 'US', 'West', 'Maui Warehouse (Kahului), HI')
('6601-KAPO', '6601-Hawaii-Campbell', 'Hawaii-Campbell', 'HAWAII', 'HI', 'HI-C', '91-210 HANUA STREET', 'KAPOLEI', 96707, 'HI', 'US', 'West', 'Campbell Warehouse (Kapolei), HI')
('6601-KAWA', '6601-Hawaii-Big Island', 'Hawaii-Big Island', 'HAWAII', 'HI', 'HI-B', '61-3785 MALUOKALANI PLACE   12', 'KAWAIHAE', 96743, 'HI', 'US', 'West', 'Big Island Warehouse (Kawaihae), HI')
('6601-LIHU', '6601-Hawaii-Kauai', 'Hawaii-Kauai', 'HAWAII', 'HI', 'HI-K', '1556 LIHUE HALEUKANA STREET', 'KAUAI', 96766, 'HI', 'US', 'West', 'Kauai Warehouse (Lihue), HI')
('7201-LASV', '7201-Nevada-Las Vegas', 'Nevada-Las Vegas', 'NEVADA', 'NV', 'NV-L', '8400 SOUTH JONES BLVD', 'LAS VEGAS', 89139, 'NV', 'US', 'West', 'Las Vegas,NV')
('7202-SPAR', '7202-Nevada-Sparks', 'Nevada-Sparks', 'NEVADA', 'NV', 'NV-S', '250 LILLARD DRIVE SUITE 101', 'SPARKS', 89434, 'NV', 'US', 'West', 'Sparks, NV')
('7601-BULK', '7601-New Mexico', 'New Mexico', 'NO', 'NM', 'NM', '123 MONTANO RD, NW', 'ALBUQUERQUE', 87107, 'NM', 'US', 'West', 'Albuquerque, NM')
('7801-DENV', '7801-Colorado', 'Colorado', 'NO', 'CO', 'CO', '22800 EAST 19TH AVENUE', 'AURORA', 80019, 'CO', 'US', 'Central', 'Denver, CO')
('8001-BULK', '8001-Washington', 'Washington', 'WA/OR', 'WA', 'WA', '1025 VALLEY AVE NW', 'PUYALLUP', 98371, 'WA', 'US', 'West', 'Puyallup, WA')
('8201-BULK', '8201-Oregon-Wilsonville', 'Oregon-Wilsonville', 'WA/OR', 'OR', 'OR', '9805 SW BOECKMAN ROAD', 'WILSONVILLE', 97070, 'OR', 'US', 'West', 'Wilsonville, OR')
('8301-1000', '8301-Iowa-Urbandale', 'Iowa-Urbandale', 'NO', 'IA', 'IA', '4377 112TH STREET', 'URBANDALE', 50322, 'IA', 'US', 'Central', 'Urbandale (Des Moines), IA')
('8701-1000', '8701-Texas-Dallas', 'Texas-Dallas', 'TEXAS', 'TX', 'TX-DA', '2001 DIPLOMAT DRIVE', 'FORT WORTH', 75234, 'TX', 'US', 'Central', 'Fort Worth, TX ')
('8702-1000', '8702-Texas-Katy', 'Texas-Katy', 'TEXAS', 'TX', 'TX-HO', '525 CANE ISLAND PARKWAY', 'KATY', 77494, 'TX', 'US', 'Central', 'Houston (Katy), TX')
('8704-1000', '8704-Texas-San Antonio', 'Texas-San Antonio', 'TEXAS', 'TX', 'TX-SA', '1002 S CALLAGHAN ROAD', 'SAN ANTONIO', 78227, 'TX', 'US', 'Central', 'San Antonio, TX')
('9201-1000', '9201-Louisiana-Saint Rose', 'Louisiana-Saint Rose', 'LOUISINA', 'LA', 'LA-NO', '111 RIVERBEND DR', 'SAINT ROSE', 70087, 'LA', 'US', 'Central', 'St. Rose (New Orleans), LA')
('9202-1000', '9202-Louisiana-Lafayette', 'Louisiana-Lafayette', 'LOUISINA', 'LA', 'LA-LA', '939 W PONT DES MOUTON RD', 'LAFAYETTE', 70507, 'LA', 'US', 'Central', 'Lafayette, LA')
('9301-1000', '9301-Arkansas-North Little Rock', 'Arkansas-North Little Rock', 'NO', 'AR', 'AR', '11101 SMITTY LANE', 'NORTH LITTLE ROCK', 72117, 'AR', 'US', 'Central', 'North Little Rock, AR')
('9401-1000', '9401-Kansas-Edwardsville', 'Kansas-Edwardsville', 'NO', 'KS', 'KS', '1100 BLAKE STREET', 'EDWARDSVILLE', 66111, 'KS', 'US', 'Central', 'Edwardsville (Lenexa), KS')
('9501-1000', '9501-Missouri-Kansas City', 'Missouri-Kansas City', 'MISSOURI', 'MO', 'MO-KC', '6201 STILWELL STREET', 'KANSAS CITY', 64120, 'MO', 'US', 'Central', 'Kansas City , MO')
('9502-1000', '9502-Missouri-Saint Charles', 'Missouri-Saint Charles', 'MISSOURI', 'MO', 'MO-SC', '1 GLAZERS WAY', 'ST. CHARLES', 63301, 'MO', 'US', 'Central', 'St. Charles (St Louis), MO')
('8501-1000', '8501-Oklahoma-Oklahoma City', 'Oklahoma-Oklahoma City', 'NO', 'OK', 'OK', '315 SOUTH 85TH EAST AVENUE', 'TULSA', 74112, 'OK', 'US', 'Central', 'Oklahoma City, OK')
('7701-1000', '7701- Tennesse', 'Tennesse', 'NO', 'TN', 'TN', '6290 SHELBY VIEW DRIVE', 'MEMPHIS', 38134, 'TN', 'US', 'East', 'Tennesse, TN')
('1111-BULK', '1111-Florida', 'Florida', 'FLN/FLS', 'FL', 'FL-S', '1234 OLD TAMPA HIGHWAY', 'LAKELAND', 33324, 'FL', 'US', 'East', 'Lakeland, FL')

In [24]:
# Empleo de update. Vamos a cambiar el estado del registro creado de Florida a Georgia
conn=sql.connect(base_de_datos)
cursor=conn.cursor()
query = """
UPDATE Bodegas_Info_tabla
SET Description = 'Georgia' WHERE DEST = '1111-BULK';
"""
cursor.execute(query)
conn.commit()
cursor.close()
conn.close()

In [25]:
# Verificacion de la modificacion del registro
conn=sql.connect(base_de_datos)
cursor=conn.cursor()
query="SELECT * FROM Bodegas_Info_tabla;"
cursor.execute(query)
datos=cursor.fetchall()
for info in datos:
    print(info)
cursor.close()
conn.close()

('1401-BULK', '1401-Florida', 'Florida', 'FL/SC', 'FL', 'FL', '4400 OLD TAMPA HIGHWAY', 'LAKELAND', 33811, 'FL', 'US', 'East', 'Lakeland, FL')
('2201-LOUI', '2201-Kentucky', 'Kentucky', 'NO', 'KY', 'KY', '2801 CONSTANT COMMENT PLACE', 'LOUISVILLE', 40299, 'KY', 'US', 'East', 'Louisville, KY')
('2501-BULK', '2501-Indiana', 'Indiana', 'NO', 'IN', 'IN', '3901 HANNA CIRCLE', 'INDIANAPOLIS', 46241, 'IN', 'US', 'Central', 'Greenwood, IN')
('3201-COLU', '3201-South Carolina', 'South Carolina', 'FL/SC', 'SC', 'SC', '7600 RICHARD STREET', 'COLUMBIA', 29209, 'SC', 'US', 'East', 'Columbia, SC')
('3501-BOLI', '3501-Illinois', 'Illinois', 'NO', 'IL', 'IL', '300 EAST CROSSROADS PARKWAY', 'BOLINGBROOK', 60440, 'IL', 'US', 'Central', 'Bolingbrook, IL')
('4201-BULK', '4201-Pennsylvania', 'Pennsylvania', 'NO', 'PA', 'PA', '536 JONES BLVD', 'POTTSTOWN', 19464, 'PA', 'US', 'East', 'Pennsylvania, PA')
('4501-LIND', '4501-New York-Linden', 'New York-Linden', 'NEW YORK', 'NY', 'NY-L', '801 West Linden Avenue', 'Linden', 7036, 'NJ', 'US', 'East', 'Linden, NY')
('4501-METR', '4501-New York-Syosset', 'New York-Syosset', 'NEW YORK', 'NY', 'NY-M', '345 UNDERHILL BLVD', 'SYOSSET', 11791, 'NY', 'US', 'East', 'Syosset, NY')
('4601-SL01', '4601-New York-Syracuse', 'New York-Syracuse', 'NEW YORK', 'NY', 'NY-U', '3063 COURT STREET', 'SYRACUSE', 13208, 'NY', 'US', 'East', 'Syracuse, NY')
('5101-1000', '5101-Ohio-Columbus', 'Ohio-Columbus', 'OHIO', 'OH', 'OH-CO', '4800 PORTH ROAD', 'COLUMBUS', 43213, 'OH', 'US', 'East', 'Columbus, OH')
('5102-1000', '5102-Ohio-Glenwillow', 'Ohio-Glenwillow', 'OHIO', 'OH', 'OH-CL', '7800 COCHRAN ROAD', 'GLENWILLOW', 44139, 'OH', 'US', 'East', 'Glenwillow (Cleveland), OH ')
('5201-BULK', '5201-Arizona', 'Arizona', 'NO', 'AZ', 'AZ', '2375 S 45th AVE', 'PHOENIX', 85043, 'AZ', 'US', 'West', 'Phoenix, AZ')
('5301-BULK', '5301-Wash DC', 'Wash DC', 'MARYLAND & CISTRIC OF COLUMBIA', 'DC', 'DC', '7001 QUAD AVENUE', 'BALTIMORE', 21237, 'MD', 'US', 'East', 'Wash DC')
('5401-BULK', '5401-Delaware', 'Delaware', 'NO', 'DE', 'DE', '615 LAMBSON LANE', 'NEW CASTLE', 19720, 'DE', 'US', 'East', 'Newcastle, DE')
('5501-BULK', '5501-Maryland', 'Maryland', 'MARYLAND & CISTRIC OF COLUMBIA', 'MD', 'MD', '7001 QUAD AVENUE', 'BALTIMORE', 21237, 'MD', 'US', 'East', 'Baltimore, MD')
('5601-BULK', '5601-Minnesota', 'Minnesota', 'Minnesota & North & South Dakota', 'MN', 'MN', '3350 4th AVENUE EAST', 'SHAKOPEE', 55379, 'MN', 'US', 'Central', 'Shakopee, MN')
('5701-NBLK', '5701-North Dakota', 'North Dakota', 'Minnesota & North & South Dakota', 'ND', 'ND', '3350 4TH AVENUE EAST', 'SHAKOPEE', 55379, 'MN', 'US', 'Central', 'North Dakota')
('5801-SBLK', '5801-South Dakota', 'South Dakota', 'Minnesota & North & South Dakota', 'SD', 'SD', '3350 4TH AVENUE EAST', 'SHAKOPEE', 55379, 'MN', 'US', 'Central', 'South Dakota')
('5901-BULK', '5901-Nebraska', 'Nebraska', 'NO', 'NE', 'NE', '4433 SOUTH 96TH STREET', 'OMAHA', 68127, 'NE', 'US', 'Central', 'Omaha, NE')
('6201-STFE', '6201-California-Santa Fe Springs', 'California-Santa Fe Springs', 'CALIFORNIA', 'CA', 'CA-S', '13500 FOSTER ROAD', 'SANTA FE SPRINGS', 90670, 'CA', 'US', 'West', 'Santa Fe, CA')
('6401-OTHR', '6401-California-Union City', 'California-Union City', 'CALIFORNIA', 'CA', 'CA-N', '1555 ATLANTIC STREET', 'UNION CITY', 94587, 'CA', 'US', 'West', 'Union City, CA')
('6601-KAHU', '6601-Hawaii-Maui ', 'Hawaii-Maui ', 'HAWAII', 'HI', 'HI-M', '231 LALO PLACE KAHULUI', 'MAUI', 96732, 'HI', 'US', 'West', 'Maui Warehouse (Kahului), HI')
('6601-KAPO', '6601-Hawaii-Campbell', 'Hawaii-Campbell', 'HAWAII', 'HI', 'HI-C', '91-210 HANUA STREET', 'KAPOLEI', 96707, 'HI', 'US', 'West', 'Campbell Warehouse (Kapolei), HI')
('6601-KAWA', '6601-Hawaii-Big Island', 'Hawaii-Big Island', 'HAWAII', 'HI', 'HI-B', '61-3785 MALUOKALANI PLACE   12', 'KAWAIHAE', 96743, 'HI', 'US', 'West', 'Big Island Warehouse (Kawaihae), HI')
('6601-LIHU', '6601-Hawaii-Kauai', 'Hawaii-Kauai', 'HAWAII', 'HI', 'HI-K', '1556 LIHUE HALEUKANA STREET', 'KAUAI', 96766, 'HI', 'US', 'West', 'Kauai Warehouse (Lihue), HI')
('7201-LASV', '7201-Nevada-Las Vegas', 'Nevada-Las Vegas', 'NEVADA', 'NV', 'NV-L', '8400 SOUTH JONES BLVD', 'LAS VEGAS', 89139, 'NV', 'US', 'West', 'Las Vegas,NV')
('7202-SPAR', '7202-Nevada-Sparks', 'Nevada-Sparks', 'NEVADA', 'NV', 'NV-S', '250 LILLARD DRIVE SUITE 101', 'SPARKS', 89434, 'NV', 'US', 'West', 'Sparks, NV')
('7601-BULK', '7601-New Mexico', 'New Mexico', 'NO', 'NM', 'NM', '123 MONTANO RD, NW', 'ALBUQUERQUE', 87107, 'NM', 'US', 'West', 'Albuquerque, NM')
('7801-DENV', '7801-Colorado', 'Colorado', 'NO', 'CO', 'CO', '22800 EAST 19TH AVENUE', 'AURORA', 80019, 'CO', 'US', 'Central', 'Denver, CO')
('8001-BULK', '8001-Washington', 'Washington', 'WA/OR', 'WA', 'WA', '1025 VALLEY AVE NW', 'PUYALLUP', 98371, 'WA', 'US', 'West', 'Puyallup, WA')
('8201-BULK', '8201-Oregon-Wilsonville', 'Oregon-Wilsonville', 'WA/OR', 'OR', 'OR', '9805 SW BOECKMAN ROAD', 'WILSONVILLE', 97070, 'OR', 'US', 'West', 'Wilsonville, OR')
('8301-1000', '8301-Iowa-Urbandale', 'Iowa-Urbandale', 'NO', 'IA', 'IA', '4377 112TH STREET', 'URBANDALE', 50322, 'IA', 'US', 'Central', 'Urbandale (Des Moines), IA')
('8701-1000', '8701-Texas-Dallas', 'Texas-Dallas', 'TEXAS', 'TX', 'TX-DA', '2001 DIPLOMAT DRIVE', 'FORT WORTH', 75234, 'TX', 'US', 'Central', 'Fort Worth, TX ')
('8702-1000', '8702-Texas-Katy', 'Texas-Katy', 'TEXAS', 'TX', 'TX-HO', '525 CANE ISLAND PARKWAY', 'KATY', 77494, 'TX', 'US', 'Central', 'Houston (Katy), TX')
('8704-1000', '8704-Texas-San Antonio', 'Texas-San Antonio', 'TEXAS', 'TX', 'TX-SA', '1002 S CALLAGHAN ROAD', 'SAN ANTONIO', 78227, 'TX', 'US', 'Central', 'San Antonio, TX')
('9201-1000', '9201-Louisiana-Saint Rose', 'Louisiana-Saint Rose', 'LOUISINA', 'LA', 'LA-NO', '111 RIVERBEND DR', 'SAINT ROSE', 70087, 'LA', 'US', 'Central', 'St. Rose (New Orleans), LA')
('9202-1000', '9202-Louisiana-Lafayette', 'Louisiana-Lafayette', 'LOUISINA', 'LA', 'LA-LA', '939 W PONT DES MOUTON RD', 'LAFAYETTE', 70507, 'LA', 'US', 'Central', 'Lafayette, LA')
('9301-1000', '9301-Arkansas-North Little Rock', 'Arkansas-North Little Rock', 'NO', 'AR', 'AR', '11101 SMITTY LANE', 'NORTH LITTLE ROCK', 72117, 'AR', 'US', 'Central', 'North Little Rock, AR')
('9401-1000', '9401-Kansas-Edwardsville', 'Kansas-Edwardsville', 'NO', 'KS', 'KS', '1100 BLAKE STREET', 'EDWARDSVILLE', 66111, 'KS', 'US', 'Central', 'Edwardsville (Lenexa), KS')
('9501-1000', '9501-Missouri-Kansas City', 'Missouri-Kansas City', 'MISSOURI', 'MO', 'MO-KC', '6201 STILWELL STREET', 'KANSAS CITY', 64120, 'MO', 'US', 'Central', 'Kansas City , MO')
('9502-1000', '9502-Missouri-Saint Charles', 'Missouri-Saint Charles', 'MISSOURI', 'MO', 'MO-SC', '1 GLAZERS WAY', 'ST. CHARLES', 63301, 'MO', 'US', 'Central', 'St. Charles (St Louis), MO')
('8501-1000', '8501-Oklahoma-Oklahoma City', 'Oklahoma-Oklahoma City', 'NO', 'OK', 'OK', '315 SOUTH 85TH EAST AVENUE', 'TULSA', 74112, 'OK', 'US', 'Central', 'Oklahoma City, OK')
('7701-1000', '7701- Tennesse', 'Tennesse', 'NO', 'TN', 'TN', '6290 SHELBY VIEW DRIVE', 'MEMPHIS', 38134, 'TN', 'US', 'East', 'Tennesse, TN')
('1111-BULK', '1111-Florida', 'Georgia', 'FLN/FLS', 'FL', 'FL-S', '1234 OLD TAMPA HIGHWAY', 'LAKELAND', 33324, 'FL', 'US', 'East', 'Lakeland, FL')

In [26]:
# Eliminacion de registros donde DEST = 1111-BULK
conn=sql.connect(base_de_datos)
cursor=conn.cursor()
query = """
DELETE FROM Bodegas_Info_tabla
WHERE DEST = '1111-BULK';
"""
cursor.execute(query)
conn.commit()
cursor.close()
conn.close()

In [27]:
# Verificacion de la eliminacion de los registros
conn=sql.connect(base_de_datos)
cursor=conn.cursor()
query="SELECT * FROM Bodegas_Info_tabla;"
cursor.execute(query)
datos=cursor.fetchall()
for info in datos:
    print(info)
cursor.close()
conn.close()

('1401-BULK', '1401-Florida', 'Florida', 'FL/SC', 'FL', 'FL', '4400 OLD TAMPA HIGHWAY', 'LAKELAND', 33811, 'FL', 'US', 'East', 'Lakeland, FL')
('2201-LOUI', '2201-Kentucky', 'Kentucky', 'NO', 'KY', 'KY', '2801 CONSTANT COMMENT PLACE', 'LOUISVILLE', 40299, 'KY', 'US', 'East', 'Louisville, KY')
('2501-BULK', '2501-Indiana', 'Indiana', 'NO', 'IN', 'IN', '3901 HANNA CIRCLE', 'INDIANAPOLIS', 46241, 'IN', 'US', 'Central', 'Greenwood, IN')
('3201-COLU', '3201-South Carolina', 'South Carolina', 'FL/SC', 'SC', 'SC', '7600 RICHARD STREET', 'COLUMBIA', 29209, 'SC', 'US', 'East', 'Columbia, SC')
('3501-BOLI', '3501-Illinois', 'Illinois', 'NO', 'IL', 'IL', '300 EAST CROSSROADS PARKWAY', 'BOLINGBROOK', 60440, 'IL', 'US', 'Central', 'Bolingbrook, IL')
('4201-BULK', '4201-Pennsylvania', 'Pennsylvania', 'NO', 'PA', 'PA', '536 JONES BLVD', 'POTTSTOWN', 19464, 'PA', 'US', 'East', 'Pennsylvania, PA')
('4501-LIND', '4501-New York-Linden', 'New York-Linden', 'NEW YORK', 'NY', 'NY-L', '801 West Linden Avenue', 'Linden', 7036, 'NJ', 'US', 'East', 'Linden, NY')
('4501-METR', '4501-New York-Syosset', 'New York-Syosset', 'NEW YORK', 'NY', 'NY-M', '345 UNDERHILL BLVD', 'SYOSSET', 11791, 'NY', 'US', 'East', 'Syosset, NY')
('4601-SL01', '4601-New York-Syracuse', 'New York-Syracuse', 'NEW YORK', 'NY', 'NY-U', '3063 COURT STREET', 'SYRACUSE', 13208, 'NY', 'US', 'East', 'Syracuse, NY')
('5101-1000', '5101-Ohio-Columbus', 'Ohio-Columbus', 'OHIO', 'OH', 'OH-CO', '4800 PORTH ROAD', 'COLUMBUS', 43213, 'OH', 'US', 'East', 'Columbus, OH')
('5102-1000', '5102-Ohio-Glenwillow', 'Ohio-Glenwillow', 'OHIO', 'OH', 'OH-CL', '7800 COCHRAN ROAD', 'GLENWILLOW', 44139, 'OH', 'US', 'East', 'Glenwillow (Cleveland), OH ')
('5201-BULK', '5201-Arizona', 'Arizona', 'NO', 'AZ', 'AZ', '2375 S 45th AVE', 'PHOENIX', 85043, 'AZ', 'US', 'West', 'Phoenix, AZ')
('5301-BULK', '5301-Wash DC', 'Wash DC', 'MARYLAND & CISTRIC OF COLUMBIA', 'DC', 'DC', '7001 QUAD AVENUE', 'BALTIMORE', 21237, 'MD', 'US', 'East', 'Wash DC')
('5401-BULK', '5401-Delaware', 'Delaware', 'NO', 'DE', 'DE', '615 LAMBSON LANE', 'NEW CASTLE', 19720, 'DE', 'US', 'East', 'Newcastle, DE')
('5501-BULK', '5501-Maryland', 'Maryland', 'MARYLAND & CISTRIC OF COLUMBIA', 'MD', 'MD', '7001 QUAD AVENUE', 'BALTIMORE', 21237, 'MD', 'US', 'East', 'Baltimore, MD')
('5601-BULK', '5601-Minnesota', 'Minnesota', 'Minnesota & North & South Dakota', 'MN', 'MN', '3350 4th AVENUE EAST', 'SHAKOPEE', 55379, 'MN', 'US', 'Central', 'Shakopee, MN')
('5701-NBLK', '5701-North Dakota', 'North Dakota', 'Minnesota & North & South Dakota', 'ND', 'ND', '3350 4TH AVENUE EAST', 'SHAKOPEE', 55379, 'MN', 'US', 'Central', 'North Dakota')
('5801-SBLK', '5801-South Dakota', 'South Dakota', 'Minnesota & North & South Dakota', 'SD', 'SD', '3350 4TH AVENUE EAST', 'SHAKOPEE', 55379, 'MN', 'US', 'Central', 'South Dakota')
('5901-BULK', '5901-Nebraska', 'Nebraska', 'NO', 'NE', 'NE', '4433 SOUTH 96TH STREET', 'OMAHA', 68127, 'NE', 'US', 'Central', 'Omaha, NE')
('6201-STFE', '6201-California-Santa Fe Springs', 'California-Santa Fe Springs', 'CALIFORNIA', 'CA', 'CA-S', '13500 FOSTER ROAD', 'SANTA FE SPRINGS', 90670, 'CA', 'US', 'West', 'Santa Fe, CA')
('6401-OTHR', '6401-California-Union City', 'California-Union City', 'CALIFORNIA', 'CA', 'CA-N', '1555 ATLANTIC STREET', 'UNION CITY', 94587, 'CA', 'US', 'West', 'Union City, CA')
('6601-KAHU', '6601-Hawaii-Maui ', 'Hawaii-Maui ', 'HAWAII', 'HI', 'HI-M', '231 LALO PLACE KAHULUI', 'MAUI', 96732, 'HI', 'US', 'West', 'Maui Warehouse (Kahului), HI')
('6601-KAPO', '6601-Hawaii-Campbell', 'Hawaii-Campbell', 'HAWAII', 'HI', 'HI-C', '91-210 HANUA STREET', 'KAPOLEI', 96707, 'HI', 'US', 'West', 'Campbell Warehouse (Kapolei), HI')
('6601-KAWA', '6601-Hawaii-Big Island', 'Hawaii-Big Island', 'HAWAII', 'HI', 'HI-B', '61-3785 MALUOKALANI PLACE   12', 'KAWAIHAE', 96743, 'HI', 'US', 'West', 'Big Island Warehouse (Kawaihae), HI')
('6601-LIHU', '6601-Hawaii-Kauai', 'Hawaii-Kauai', 'HAWAII', 'HI', 'HI-K', '1556 LIHUE HALEUKANA STREET', 'KAUAI', 96766, 'HI', 'US', 'West', 'Kauai Warehouse (Lihue), HI')
('7201-LASV', '7201-Nevada-Las Vegas', 'Nevada-Las Vegas', 'NEVADA', 'NV', 'NV-L', '8400 SOUTH JONES BLVD', 'LAS VEGAS', 89139, 'NV', 'US', 'West', 'Las Vegas,NV')
('7202-SPAR', '7202-Nevada-Sparks', 'Nevada-Sparks', 'NEVADA', 'NV', 'NV-S', '250 LILLARD DRIVE SUITE 101', 'SPARKS', 89434, 'NV', 'US', 'West', 'Sparks, NV')
('7601-BULK', '7601-New Mexico', 'New Mexico', 'NO', 'NM', 'NM', '123 MONTANO RD, NW', 'ALBUQUERQUE', 87107, 'NM', 'US', 'West', 'Albuquerque, NM')
('7801-DENV', '7801-Colorado', 'Colorado', 'NO', 'CO', 'CO', '22800 EAST 19TH AVENUE', 'AURORA', 80019, 'CO', 'US', 'Central', 'Denver, CO')
('8001-BULK', '8001-Washington', 'Washington', 'WA/OR', 'WA', 'WA', '1025 VALLEY AVE NW', 'PUYALLUP', 98371, 'WA', 'US', 'West', 'Puyallup, WA')
('8201-BULK', '8201-Oregon-Wilsonville', 'Oregon-Wilsonville', 'WA/OR', 'OR', 'OR', '9805 SW BOECKMAN ROAD', 'WILSONVILLE', 97070, 'OR', 'US', 'West', 'Wilsonville, OR')
('8301-1000', '8301-Iowa-Urbandale', 'Iowa-Urbandale', 'NO', 'IA', 'IA', '4377 112TH STREET', 'URBANDALE', 50322, 'IA', 'US', 'Central', 'Urbandale (Des Moines), IA')
('8701-1000', '8701-Texas-Dallas', 'Texas-Dallas', 'TEXAS', 'TX', 'TX-DA', '2001 DIPLOMAT DRIVE', 'FORT WORTH', 75234, 'TX', 'US', 'Central', 'Fort Worth, TX ')
('8702-1000', '8702-Texas-Katy', 'Texas-Katy', 'TEXAS', 'TX', 'TX-HO', '525 CANE ISLAND PARKWAY', 'KATY', 77494, 'TX', 'US', 'Central', 'Houston (Katy), TX')
('8704-1000', '8704-Texas-San Antonio', 'Texas-San Antonio', 'TEXAS', 'TX', 'TX-SA', '1002 S CALLAGHAN ROAD', 'SAN ANTONIO', 78227, 'TX', 'US', 'Central', 'San Antonio, TX')
('9201-1000', '9201-Louisiana-Saint Rose', 'Louisiana-Saint Rose', 'LOUISINA', 'LA', 'LA-NO', '111 RIVERBEND DR', 'SAINT ROSE', 70087, 'LA', 'US', 'Central', 'St. Rose (New Orleans), LA')
('9202-1000', '9202-Louisiana-Lafayette', 'Louisiana-Lafayette', 'LOUISINA', 'LA', 'LA-LA', '939 W PONT DES MOUTON RD', 'LAFAYETTE', 70507, 'LA', 'US', 'Central', 'Lafayette, LA')
('9301-1000', '9301-Arkansas-North Little Rock', 'Arkansas-North Little Rock', 'NO', 'AR', 'AR', '11101 SMITTY LANE', 'NORTH LITTLE ROCK', 72117, 'AR', 'US', 'Central', 'North Little Rock, AR')
('9401-1000', '9401-Kansas-Edwardsville', 'Kansas-Edwardsville', 'NO', 'KS', 'KS', '1100 BLAKE STREET', 'EDWARDSVILLE', 66111, 'KS', 'US', 'Central', 'Edwardsville (Lenexa), KS')
('9501-1000', '9501-Missouri-Kansas City', 'Missouri-Kansas City', 'MISSOURI', 'MO', 'MO-KC', '6201 STILWELL STREET', 'KANSAS CITY', 64120, 'MO', 'US', 'Central', 'Kansas City , MO')
('9502-1000', '9502-Missouri-Saint Charles', 'Missouri-Saint Charles', 'MISSOURI', 'MO', 'MO-SC', '1 GLAZERS WAY', 'ST. CHARLES', 63301, 'MO', 'US', 'Central', 'St. Charles (St Louis), MO')
('8501-1000', '8501-Oklahoma-Oklahoma City', 'Oklahoma-Oklahoma City', 'NO', 'OK', 'OK', '315 SOUTH 85TH EAST AVENUE', 'TULSA', 74112, 'OK', 'US', 'Central', 'Oklahoma City, OK')
('7701-1000', '7701- Tennesse', 'Tennesse', 'NO', 'TN', 'TN', '6290 SHELBY VIEW DRIVE', 'MEMPHIS', 38134, 'TN', 'US', 'East', 'Tennesse, TN')